# Generated by Django 3.0.7 on 2020-10-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
    ]
